### ISSUE TITLE
Use `ghc-pkg-lib` to speed up metadata collection and fix some UI lockup issues

### ISSUE THREAD

**Issue by hamishmack** [leksah/leksah-server#13]
I think that when we collect workspace metadata the UI thread blocks running `ghc-pkg list --simple-output` once per package in the workspace.  ghc-pkg takes about 0.1s to run (at least on my machine).  The delay is really annoying when you have 20 or 30 packages in your workspace!

@JPMoresmau am I right in thinking that if we change `getInstalledPackageIds'` in `IDE.Utils.FileUtils` use `ghc-pkg-lib` it might be much faster (since it will avoid the process startup time)?

**Comment by JPMoresmau** [comment]
I don't know really. Let me resurrect  ghc-pkg-lib, test it better and make some tests. If it's faster I can make the switch.

**Comment by JPMoresmau** [comment]
Mmmhhh, added a test to ghc-pkg-lib and some rough timings at https://github.com/JPMoresmau/ghc-pkg-lib/blob/master/test/Main.hs, calling the executable is faster than the library. Do we really need to launch ghc-pkg for each package? Couldn't we cache the result?

**Comment by hamishmack** [comment]
Yes we should cache the results.  Even if we just cache them for 2 seconds it should make a big difference when lots of packages are in the workspace.

Also if we add a workspace update thread we should be able to avoid blocking the UI at all.  We could do the queue like [the HLint one](https://github.com/leksah/leksah/blob/master/src/IDE/HLint.hs#L85) so that it only queues a request for a package update if one is not already in the queue.

**Comment by JPMoresmau** [comment]
I can see we're using ghc-pkg list to calculate fitting dependencies on each package. Why don't we calculate the list once and pass it to each package? Basically once in https://github.com/leksah/leksah/blob/f75b59294e27e9f43727aaa40a5a78d999b30ab3/src/IDE/Metainfo/Provider.hs#L259 and pass it to calls to `updatePackageInfo`

**Comment by hamishmack** [comment]
Nice fix!
